### ISSUE TITLE
To Whoever Facing Problems Running the Exercises on WSL (non-Docker Workaround)

### ISSUE THREAD

**Issue by shaolang** [udacity/cd0581-building-a-reproducible-model-workflow-exercises#20]
To whoever taking this course in year 2024 (and beyond)

Until Udacity updates the contents, the course is pretty stuck in year 2022. I'm sharing what works for me on WSL (didn't try on *nix or Mac yet), but it probably will work for them too. I gave up "fighting" the versions issue after many hair-pulling evenings.

## Miniconda
After installing the latest and the greatest, create a new conda environment with Python version:
* 3.7 as follows (I named it as py37, to make it obvious), if you are using WSL.
* 3.8 (change the arguments according), if you are using Mac.
```
$ conda create -n py37 python=3.7
$ conda activate py37
```

Then install some essential packages as specified as follows with pip  (don't worry, this won't "taint" you system/base Python's site packages):
```
# if you are using WSL
$ pip install protobuf==3.20.3 mlflow=1.14.1 numpy=1.18.5 wandb==0.10.21 

# if you are using Mac
$ pip install protobuf==3.20.3 mlflow=1.14.1 wandb==0.10.21
$ pip uninstall numpy
$ conda install numpy=1.19.5   

# install the following regardless of the OS you are using
$ pip install hydra-core==1.3.2
```

## Exercises
In every `conda.yml` file (remember those in sub-directories too), add the lines as stated in comments:

```yaml
name: whatever
dependencies:
  - python=3.7        # add this, always (or python=3.8 if you are using Mac)
  - numpy=1.18.5      # add this when mlflow or pandas is listed as a dependency (or numpy=1.19.5 if you are using Mac)
  - Jinja2=3.0.3      # add this when pandas-profiling is listed as a dependency
  - jupyterlab=3.0.12 # remove this when it is listed as a dependency
  - notebook          # add this when jupyterlab is listed as a dependency; no need to specify the version
  - pip:
    - protobuf==3.20.3   # add this when wandb is listed as a dependency
```

With these, most of the dependencies stated in the exercise's `conda.yml` should just work (as of Mar 2024). For those that don't (especially the transitive dependencies), search in conda forge or pypi for versions that were published in 2022 (preferably in Mar 2022 or earlier).

In the exercise where `jupyterlab` dependency is replaced with notebook, change the command in the `MLProject` to
`jupyter notebook`.

## Misc
~When I have time, I'll try the same setup directly on Windows (instead of WSL) and Mac.~ Directly/Natively on Windows won't work 'cos of the use of `$(echo {hydra_options})` in some of the MLProject files.
Mac users may have to make some package version updates discovered along the way. I only randomly chose the exercises to test the setup on Mac, and discovered that some dependencies won't work, e.g., `matplotlib` 3.2.2 needs to be replaced with 3.5.3 (for exercise 12). 

Also, whoever having successes in setting things differently, please add to this "issue" to help future learners.
